import { REFERENCE_LOANS, SMALL_SEVEN, SNAPSHOT_DATE } from "@/lib/seed-portfolio";
import { simulate, monthlyInterest, minimumPayment, monthlyFee } from "@/lib/payoff";
const L = REFERENCE_LOANS;
const total = L.reduce((s,l)=>s+l.current_balance,0);
const interest = L.reduce((s,l)=>s+monthlyInterest(l,l.current_balance),0);
const fees = L.reduce((s,l)=>s+monthlyFee(l),0);
const mins = L.reduce((s,l)=>s+minimumPayment(l,l.current_balance)+monthlyFee(l),0);
console.log({total, weighted: L.reduce((s,l)=>s+l.nominal_rate*l.current_balance,0)/total, interest, fees, mins, toDebt: mins-interest-fees});
const brocc=[L[0]!];
const b1=simulate(brocc,0,"baseline",SNAPSHOT_DATE);
console.log("brocc",b1.months,b1.totalInterest, b1.schedule[0]?.payments["brocc"]);
const b2=simulate(brocc,6000,"avalanche",SNAPSHOT_DATE);
console.log("brocc+6000",b2.months,b2.totalInterest);
const brixo=[L.find(l=>l.id==="brixo")!];
const x=simulate(brixo,0,"baseline",SNAPSHOT_DATE);
console.log("brixo",x.months,x.totalInterest,x.schedule[0]?.payments["brixo"]);
const nm=L.find(l=>l.id==="northmill")!;
console.log("northmill m1", monthlyInterest(nm,nm.current_balance)+330);
const small=L.filter(l=>SMALL_SEVEN.includes(l.id));
const smallSum=small.reduce((s,l)=>s+l.current_balance,0);
const smallCost=small.reduce((s,l)=>s+monthlyInterest(l,l.current_balance)+monthlyFee(l),0);
const smallMins=small.reduce((s,l)=>s+minimumPayment(l,l.current_balance)+monthlyFee(l),0);
console.log({smallSum, smallCost, smallMins, roi: smallCost*12/smallSum});
const rest=L.filter(l=>!SMALL_SEVEN.includes(l.id));
const after=simulate(rest,13470-rest.reduce((s,l)=>s+minimumPayment(l,l.current_balance)+monthlyFee(l),0),"avalanche",SNAPSHOT_DATE);
console.log("after infusion",after.months,after.totalInterest,after.perLoan.map(p=>[p.name,p.payoffMonth]));
const all=simulate(L,13470-mins,"avalanche",SNAPSHOT_DATE);
console.log("no infusion",all.months,all.totalInterest);
