/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedBudgetplanRouteImport } from './routes/_authenticated/budgetplan'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKopbeslutRouteImport } from './routes/_authenticated/kopbeslut'
import { Route as AuthenticatedLackorRouteImport } from './routes/_authenticated/lackor'
import { Route as AuthenticatedLanRouteImport } from './routes/_authenticated/lan'
import { Route as AuthenticatedOnskelistaRouteImport } from './routes/_authenticated/onskelista'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedSparandeRouteImport } from './routes/_authenticated/sparande'
import { Route as AuthenticatedTransaktionerRouteImport } from './routes/_authenticated/transaktioner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetplanRoute = AuthenticatedBudgetplanRouteImport.update({
  id: '/budgetplan',
  path: '/budgetplan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKopbeslutRoute = AuthenticatedKopbeslutRouteImport.update({
  id: '/kopbeslut',
  path: '/kopbeslut',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLackorRoute = AuthenticatedLackorRouteImport.update({
  id: '/lackor',
  path: '/lackor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLanRoute = AuthenticatedLanRouteImport.update({
  id: '/lan',
  path: '/lan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnskelistaRoute = AuthenticatedOnskelistaRouteImport.update({
  id: '/onskelista',
  path: '/onskelista',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSparandeRoute = AuthenticatedSparandeRouteImport.update({
  id: '/sparande',
  path: '/sparande',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransaktionerRoute =
  AuthenticatedTransaktionerRouteImport.update({
    id: '/transaktioner',
    path: '/transaktioner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/budgetplan': typeof AuthenticatedBudgetplanRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kopbeslut': typeof AuthenticatedKopbeslutRoute
  '/lackor': typeof AuthenticatedLackorRoute
  '/lan': typeof AuthenticatedLanRoute
  '/onskelista': typeof AuthenticatedOnskelistaRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/sparande': typeof AuthenticatedSparandeRoute
  '/transaktioner': typeof AuthenticatedTransaktionerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/budgetplan': typeof AuthenticatedBudgetplanRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kopbeslut': typeof AuthenticatedKopbeslutRoute
  '/lackor': typeof AuthenticatedLackorRoute
  '/lan': typeof AuthenticatedLanRoute
  '/onskelista': typeof AuthenticatedOnskelistaRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/sparande': typeof AuthenticatedSparandeRoute
  '/transaktioner': typeof AuthenticatedTransaktionerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/budgetplan': typeof AuthenticatedBudgetplanRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kopbeslut': typeof AuthenticatedKopbeslutRoute
  '/_authenticated/lackor': typeof AuthenticatedLackorRoute
  '/_authenticated/lan': typeof AuthenticatedLanRoute
  '/_authenticated/onskelista': typeof AuthenticatedOnskelistaRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/sparande': typeof AuthenticatedSparandeRoute
  '/_authenticated/transaktioner': typeof AuthenticatedTransaktionerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budget'
    | '/budgetplan'
    | '/coach'
    | '/dashboard'
    | '/kopbeslut'
    | '/lackor'
    | '/lan'
    | '/onskelista'
    | '/plan'
    | '/sparande'
    | '/transaktioner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budget'
    | '/budgetplan'
    | '/coach'
    | '/dashboard'
    | '/kopbeslut'
    | '/lackor'
    | '/lan'
    | '/onskelista'
    | '/plan'
    | '/sparande'
    | '/transaktioner'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/budget'
    | '/_authenticated/budgetplan'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/kopbeslut'
    | '/_authenticated/lackor'
    | '/_authenticated/lan'
    | '/_authenticated/onskelista'
    | '/_authenticated/plan'
    | '/_authenticated/sparande'
    | '/_authenticated/transaktioner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgetplan': {
      id: '/_authenticated/budgetplan'
      path: '/budgetplan'
      fullPath: '/budgetplan'
      preLoaderRoute: typeof AuthenticatedBudgetplanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kopbeslut': {
      id: '/_authenticated/kopbeslut'
      path: '/kopbeslut'
      fullPath: '/kopbeslut'
      preLoaderRoute: typeof AuthenticatedKopbeslutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lackor': {
      id: '/_authenticated/lackor'
      path: '/lackor'
      fullPath: '/lackor'
      preLoaderRoute: typeof AuthenticatedLackorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lan': {
      id: '/_authenticated/lan'
      path: '/lan'
      fullPath: '/lan'
      preLoaderRoute: typeof AuthenticatedLanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onskelista': {
      id: '/_authenticated/onskelista'
      path: '/onskelista'
      fullPath: '/onskelista'
      preLoaderRoute: typeof AuthenticatedOnskelistaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sparande': {
      id: '/_authenticated/sparande'
      path: '/sparande'
      fullPath: '/sparande'
      preLoaderRoute: typeof AuthenticatedSparandeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transaktioner': {
      id: '/_authenticated/transaktioner'
      path: '/transaktioner'
      fullPath: '/transaktioner'
      preLoaderRoute: typeof AuthenticatedTransaktionerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedBudgetplanRoute: typeof AuthenticatedBudgetplanRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKopbeslutRoute: typeof AuthenticatedKopbeslutRoute
  AuthenticatedLackorRoute: typeof AuthenticatedLackorRoute
  AuthenticatedLanRoute: typeof AuthenticatedLanRoute
  AuthenticatedOnskelistaRoute: typeof AuthenticatedOnskelistaRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedSparandeRoute: typeof AuthenticatedSparandeRoute
  AuthenticatedTransaktionerRoute: typeof AuthenticatedTransaktionerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedBudgetplanRoute: AuthenticatedBudgetplanRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKopbeslutRoute: AuthenticatedKopbeslutRoute,
  AuthenticatedLackorRoute: AuthenticatedLackorRoute,
  AuthenticatedLanRoute: AuthenticatedLanRoute,
  AuthenticatedOnskelistaRoute: AuthenticatedOnskelistaRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedSparandeRoute: AuthenticatedSparandeRoute,
  AuthenticatedTransaktionerRoute: AuthenticatedTransaktionerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
